#ifndef SYSCFG_INTERFACE_H_
#define SYSCFG_INTERFACE_H_

#include <stdint.h>

typedef enum
{
    SYSCFG_EXTI0_LINE = 0,
    SYSCFG_EXTI1_LINE,
    SYSCFG_EXTI2_LINE,
    SYSCFG_EXTI3_LINE,
    SYSCFG_EXTI4_LINE,
    SYSCFG_EXTI5_LINE,
    SYSCFG_EXTI6_LINE,
    SYSCFG_EXTI7_LINE,
    SYSCFG_EXTI8_LINE,
    SYSCFG_EXTI9_LINE,
    SYSCFG_EXTI10_LINE,
    SYSCFG_EXTI11_LINE,
    SYSCFG_EXTI12_LINE,
    SYSCFG_EXTI13_LINE,
    SYSCFG_EXTI14_LINE,
    SYSCFG_EXTI15_LINE,
    SYSCFG_PVD_LINE,
    SYSCFG_RTC_ALARM_LINE,
    SYSCFG_OTG_FS_WKUP_LINE,
    SYSCFG_OTG_HS_WKUP_LINE = 20,
    SYSCFG_TAMP_STAMP_LINE,
    SYSCFG_RTC_WKUP_LINE
} SYSCFG_LineNumber_t;

typedef enum
{
    SYSCFG_PORTA=0,
    SYSCFG_PORTB,
    SYSCFG_PORTC,
    SYSCFG_PORTD,
    SYSCFG_PORTE,
    SYSCFG_PORTF,
    SYSCFG_PORTG,
    SYSCFG_PORTH
} SYSCFG_Port_t;

uint8_t SYSCFG_u8SetEXTIPort(SYSCFG_LineNumber_t Copy_LineNumber, SYSCFG_Port_t Copy_Port);

#endif /* SYSCFG_INTERFACE_H_ */
